services:
  - type: web
    name: bluestock-ipo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ipo_project.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bluestock-ipo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: bluestock-ipo-db
    databaseName: bluestock_ipo_db
    user: bluestock_ipo_db_user
